version: '3.7'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: flypass
      MYSQL_USER: user
      MYSQL_PASSWORD: Admin123*
      MYSQL_ROOT_PASSWORD: Admin123*
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5

  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/flypass
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: Admin123*
      CUSTOMER_CONTAINER: customer
      TRANSACCION_CONTAINER: transaccion

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    depends_on:
      - account
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/flypass
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: Admin123*
      ACCOUNT_CONTAINER: account
      TRANSACCION_CONTAINER: transaccion

  transaccion:
    build:
      context: ./transaccion
      dockerfile: Dockerfile
    depends_on:
      - customer
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/flypass
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: Admin123*
      ACCOUNT_CONTAINER: account
      CUSTOMER_CONTAINER: customer

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - transaccion
    ports:
      - "8000:8000"
    environment:
      ACCOUNT_CONTAINER: account
      CUSTOMER_CONTAINER: customer
      TRANSACCION_CONTAINER: transaccion